version: '3.1'
services:
  stats-server:
    build: ./stats
    image: stats
    container_name: stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=stats-db
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore
      - DB_HOST=stats-db
      - DB_PORT=5432

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore

  ewm-service:
    build: ./main
    image: main
    container_name: main
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - DB_NAME=ewm-db
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - STATS_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "7541:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore
